WebApplication4/WebApplication4/Controllers/icerikController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;
using PagedList;

namespace WebApplication4.Controllers
{
    public class icerikController : Controller
    {
        private kitamagvtEntities db = new kitamagvtEntities();

        // GET: icerik
        public ActionResult Index(int? page,String arama)
        {
            var icerikler = from s in db.icerik select s;

            if (!String.IsNullOrEmpty(arama))
            {
                icerikler = icerikler.Where(s => s.baslik.ToUpper().Contains(arama.ToUpper()));
            }

            var res = icerikler.ToList().ToPagedList(page ?? 1, 8);

            return View(res);
        }

        // GET: icerik/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            icerik icerik = db.icerik.Find(id);
            if (icerik == null)
            {
                return HttpNotFound();
            }
            return View(icerik);
        }

        // GET: icerik/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: icerik/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "icerikID,baslik,kisaaciklama,resimurl,kategori,kitapismi,yayınevi,yazar,ozet,bilgiler")] icerik icerik)
        {
            if (ModelState.IsValid)
            {
                db.icerik.Add(icerik);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(icerik);
        }

        
        // GET: icerik/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            icerik icerik = db.icerik.Find(id);
            if (icerik == null)
            {
                return HttpNotFound();
            }
            return View(icerik);
        }

        // POST: icerik/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "icerikID,baslik,kisaaciklama,resimurl,kategori,kitapismi,yayınevi,yazar,ozet,bilgiler")] icerik icerik)
        {
            if (ModelState.IsValid)
            {
                db.Entry(icerik).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(icerik);
        }

        // GET: icerik/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            icerik icerik = db.icerik.Find(id);
            if (icerik == null)
            {
                return HttpNotFound();
            }
            return View(icerik);
        }

        // POST: icerik/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            icerik icerik = db.icerik.Find(id);
            db.icerik.Remove(icerik);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication4/WebApplication4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - KitaMag</title>
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/index.css")
    @Styles.Render("~/Content/index.css")

   

</head>



<body>

        <!-- Ana menü-->
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#ana-menu">
                <span class="sr-only"></span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="">KitaMag</a>
            <div class="navbar-collapse collapse" id="ana-menu">

                <ul class="nav navbar-nav" align="right">
                    
                    <li>@Html.ActionLink(WebApplication4.Resources.HomeTexts.Home, "Index", "Home")</li>
                    <li>@Html.ActionLink(WebApplication4.Resources.HomeTexts.About, "About", "Home")</li>
                    <li>@Html.ActionLink(WebApplication4.Resources.HomeTexts.Contact, "Contact", "Home")</li>
                    <li>@Html.ActionLink(WebApplication4.Resources.HomeTexts.Language, "Index", "Language")</li>
                   

                </ul>
                @if (Session["KULLANICIADI"] == null)
                {
                    <div class="saglama">

                        <a href="@Url.Action("Create","KULLANICILAR")"><button class="btn btn-danger " role="button">  <b class="glyphicon glyphicon-user f2 "></b>&nbsp;&nbsp; @WebApplication4.Resources.HomeTexts.Register &nbsp;&nbsp;</button> </a> 
                        <a href="@Url.Action("GIRIS","KULLANICILAR")"><button class="btn btn-warning " align="right" role="button">  <b class="glyphicon glyphicon-log-in f2"></b>&nbsp;&nbsp; @WebApplication4.Resources.HomeTexts.LogIn &nbsp;&nbsp;</button></a>
                    </div>
                }

                else
                {
                    <ul class="nav navbar-nav pull-right">
                        
                                         
                        <li>@Html.ActionLink("Admin Paneli", "Index", "icerik")</li>
                        <li>@Html.ActionLink(WebApplication4.Resources.HomeTexts.Logout, "CIKIS", "KULLANICILAR")</li>
                    </ul>
                }






            </div>


        </div>

     

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - KitaMag - @WebApplication4.Resources.HomeTexts.Footer </p>
              
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>